# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wsl_Ubuntu_nbdev',
                'doc_host': 'https://NaveenDeepak.github.io',
                'git_url': 'https://github.com/NaveenDeepak/wsl_Ubuntu_nbdev',
                'lib_path': 'wsl_Ubuntu_nbdev'},
  'syms': {'wsl_Ubuntu_nbdev.core': {'wsl_Ubuntu_nbdev.core.foo': ('core.html#foo', 'wsl_Ubuntu_nbdev/core.py')}}}