# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wsl_Ubuntu_nbdev',
                'doc_host': 'https://NaveenDeepak.github.io',
                'git_url': 'https://github.com/NaveenDeepak/wsl_Ubuntu_nbdev',
                'lib_path': 'wsl_Ubuntu_nbdev'},
  'syms': { 'wsl_Ubuntu_nbdev.start': { 'wsl_Ubuntu_nbdev.start.HelloSayer': ('start.html#hellosayer', 'wsl_Ubuntu_nbdev/start.py'),
                                        'wsl_Ubuntu_nbdev.start.HelloSayer.__init__': ( 'start.html#hellosayer.__init__',
                                                                                        'wsl_Ubuntu_nbdev/start.py'),
                                        'wsl_Ubuntu_nbdev.start.HelloSayer.say': ('start.html#hellosayer.say', 'wsl_Ubuntu_nbdev/start.py'),
                                        'wsl_Ubuntu_nbdev.start.foo': ('start.html#foo', 'wsl_Ubuntu_nbdev/start.py'),
                                        'wsl_Ubuntu_nbdev.start.say_hello': ('start.html#say_hello', 'wsl_Ubuntu_nbdev/start.py')}}}