# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_start.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello', 'HelloSayer']

# %% ../nbs/00_start.ipynb 3
def foo(): pass

# %% ../nbs/00_start.ipynb 4
def say_hello(to):
    "Say hello to somebody"
    return 'Hello {}'.format(to)

# %% ../nbs/00_start.ipynb 6
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to
        
    def say(self):
        "Do the saying"
        return say_hello(self.to)
